---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to the STAT 5014 website for Fall 2021.

On this site, you will find all the material we will go over in class, all assignments, and instructions for submitting homeworks.

<ins>What this class is:</ins> a 0-60 run-through of R (and scripting/programming in Statistics) for those of you who had more pen/paper programs prior to this.

<ins>What this class is not:</ins> a fundamentals of computing course.  

We do not dive deep into the inerts of R and how to squeeze performance out of it.  We do, however, talk about ways to do things more intentionally that may in indeed result in speed improvements.  More importantly, we discuss ways to organize yourself that are both Reproducible and adher to Good Programming Practices.  We also rely on Git to submit homeworks.  More on that in class.  While doing all of this, I hope you take away short cuts, tips and tricks to make your work more professional and you more effective as a data scientist.

#### Topics

The course will include, but is not restricted to, the following programming topics:

+ R, Rmarkdown, Rnotebooks
+ Git as a code repository
+ Functions, conditional statements and loops in R
+ Base and grammer of graphics (ggplot2) in R
+ Apply family of functions in R
+ Matrix and vector math in R
+ Parallel computing
+ Basics of Python programming.
+ JMP and SAS (outside class lectures)

\noindent In the process of learning the above programming methods and platforms, we may also explore the following statistical methods:

+ Exploratory Data Analysis tools
+ Linear regression
+ ANOVA
+ Monte Carlo procedures
+ Power


