---
title: "Stat 5014 Fall 2020 Schedule"
author: "Robert Settlage"
date: "2021-08-18"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
header-includes: \setlength\parindent{24pt} \usepackage{MnSymbol} \usepackage{mathrsfs}
---

This is the tentative schedule for the 2021 Fall semester.
  
### Office and logistics

9:05-9:55 a.m.  Wednesday, Seitz 207
--------------  ---------------------------------------
CRN:            90391
Office:         Torgersen 3050
Email:          rsettlag@vt.edu
Office hours:   By appointment: Zoom or in person
Course Website: https://rsettlage.github.io/STAT5104_Fall2021/
--------------  ---------------------------------------

### Tentative schedule

Suggested schedule, you can speed ahead.
*Denotes homework due by date (you can turn in early)

|Lecture | Date      | Topic
|--------|:---------:|------------------------------------------------------------------ 
|        |           | **MODULE 1 -- R Bootcamp for Reproducible Research**  
|1       | 25-Aug    | Introductions, R, Rstudio, Rmarkdown, LaTeX, Git and Reproducible Research
|        |  1-Sep*   | No class
|2	     |  8-Sep    | Data structures, plotting basics, Reproducible Research and (some) Git
|3	     | 15-Sep*   | Base graphics, multi panel plots
|4	     | 22-Sep    | ggplot2
|        |           | **MODULE 2 -- Munging and wrangling**
|5	     | 29-Sep*   | Loading, munging, summarizing data using tidyverse 
|6	     |  6-Oct    | R functions, logic, good programming practices
|7	     | 13-Oct*   | R Vector/matrix manipulations and math, speed considerations
|8	     | 20-Oct    | R's Apply family of functions
|9	     | 27-Oct*   | Parallel computing in R, parXapply, foreach and dopar
|        |           | **MODULE 3 -- Working with others in R**  
|10	     |  3-Nov    | Interactive Visualizations and Dashboards  
|11	     | 10-Nov*   | GUIs for working with collaborators  
|        |           | **MODULE 4 -- Deep Learning and some Python**  
|12	     | 17-Nov    | Deep Learning using Keras in R  
|13	     | 24-Nov    | No class -- Thanksgiving  
|- 	     |  1-Dec*   | Python and Jupyter Notebooks  
|14	     |  8-Dec*   | More Python (Final projects due)  
|-       | ------    | Final -- none  


